{% set name = "skweak" %}
{% set version = "0.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/skweak-{{ version }}.tar.gz
  sha256: 640e3849f83bae6adcf45948be335fa33732aa5b97111d6df2fc1b6c5dfbca2e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - hmmlearn >=0.2.5,<=0.2.7
    # Somehow pip check says: "blis 1.0.1 has requirement numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4."
    - numpy <3.0.0,>=2.0.0
    - pandas >=0.23
    - python >={{ python_min }}
    - spacy >=3.0

test:
  imports:
    - skweak
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/NorskRegnesentral/skweak
  summary: Software toolkit for weak supervision in NLP
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
